# Generated by Django 4.2.5 on 2023-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_ordermodel_reservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu_images/")),
            ],
        ),
    ]
